[package]
name = "File_Write"
version = "0.1.0"
authors = ["e185760 <e185760@ie.u-ryukyu.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
